spring.application.name=prompt-run

spring.h2.console.enabled=true

# H2 Driver -> MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/prompt_run_db?serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1234

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=P5a3StcOuFSO2/PYazFeAc5KrHI++Ki6FbT/7QGPceMoIm6oiT82UXWgySIKwnwBX8HTReK1pY+/h7B9ugoLRA==

# MyPage Image Upload
spring.web.resources.static-locations=classpath:/static/,classpath:/image/

# Mocking Test
spring.profiles.active=mock

# ???? ??? ?? ?? ?? (?? ??? ?? ??)
app.file.upload-dir=C:/ProjectPrograming/DongA/WebPrograming/promptrun/upload
