spring.application.name=prompt-run

spring.h2.console.enabled=true

# H2 Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=P5a3StcOuFSO2/PYazFeAc5KrHI++Ki6FbT/7QGPceMoIm6oiT82UXWgySIKwnwBX8HTReK1pY+/h7B9ugoLRA==
